project_id = "yzlfqllwusfnhigtezfo"

[functions.seed-admin]
verify_jwt = true

[functions.user-management]
verify_jwt = false

[functions.cleanup-old-documents]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.check-stock-alerts]
verify_jwt = false

[functions.wms-assistant]
verify_jwt = false
